apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: svc-s390x
    namespace: default
    labels:
      demo: multiarch
  spec:
    type: ClusterIP
    selector:
      kubevirt.io/domain: fedora-s390x
    ports:
    - name: http
      port: 80
      targetPort: 80
- apiVersion: v1
  kind: Service
  metadata:
    name: svc-x86
    namespace: default
    labels:
      demo: multiarch
  spec:
    type: ClusterIP
    selector:
      kubevirt.io/domain: fedora-x86
    ports:
    - name: http
      port: 80
      targetPort: 80
- apiVersion: v1
  kind: Service
  metadata:
    name: svc-landing
    namespace: default
    labels:
      app: multiarch-landing
      demo: multiarch
  spec:
    type: ClusterIP
    selector:
      app: multiarch-landing
    ports:
    - name: http
      port: 80
      targetPort: 8080
